Habercim/Habercim/Controllers/MansetlerController.cs
using Habercim.DAL;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Habercim.Controllers
{
    public class MansetlerController : Controller
    {
        HabercimDbContext db = new HabercimDbContext();

        [ChildActionOnly]
        public ActionResult Manset()
        {
            var manset = db.Mansetler.ToList();
            return View(manset);

        }
    }
}

Habercim/Habercim/Controllers/MenuController.cs
using Habercim.DAL;
using Habercim.Models;
using Microsoft.Owin.Security;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Habercim.Controllers
{
    public class MenuController : Controller
    {
        HabercimDbContext db = new HabercimDbContext();
        ApplicationDbContext applicationDbContext = new ApplicationDbContext();


        [ChildActionOnly]
        public ActionResult KategoriMenu()
        {
            var kategoriler = db.Turler.ToList();
            return View(kategoriler);
        }
        [ChildActionOnly]
        public ActionResult UstMenu()
        {
            if (Request.IsAuthenticated)
            {
                var kullanici = applicationDbContext.Users.
                    Where(x => x.Email == AuthenticationManager.User.Identity.Name).First();
                var kullaniciBilgi = db.Kullanicilar.Where(x => x.KullaniciId == kullanici.KullaniciTipId).First();

                ViewBag.AdSoyad = kullaniciBilgi.AdSoyad;
                return View();
            }
            return View();
        }
        IAuthenticationManager AuthenticationManager
        {
            get
            {
                return HttpContext.GetOwinContext().Authentication;
            }
        }
    }
}

Habercim/Habercim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>@ViewBag.Title</title>
    <link href="~/Content/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/Content/css/prettyPhoto.css" rel="stylesheet">
    <link href="~/Content/css/price-range.css" rel="stylesheet">
    <link href="~/Content/css/animate.css" rel="stylesheet">
    <link href="~/Content/css/main.css" rel="stylesheet">
    <link href="~/Content/css/responsive.css" rel="stylesheet">

    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="~/Content/images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="~/Content/images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="~/Content/images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="~/Content/images/ico/apple-touch-icon-57-precomposed.png">

    <style>

    </style>
</head><!--/head-->
<body>
    <header id="header"><!--header-->
		
		
		<div class="header-middle"><!--header-middle-->
			<div class="container">
				<div class="row">
					<div class="col-sm-4">
						<div class="logo pull-left">
							<a href="~/Home"><img src="~/Content/images/home/logo.png" alt=""></a>
						</div>
					</div>
					@{ Html.RenderAction("UstMenu", "Menu");}
				</div>
			</div>
		</div><!--/header-middle-->
        <div class="header-bottom">
            <!--header-bottom-->
            <div class="container">
                <div class="row">
                    <div class="col-sm-9">
                        <div class="navbar-header">
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="sr-only">Toggle navigation</span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>
                        <div class="mainmenu pull-left">
                            <ul class="nav navbar-nav collapse navbar-collapse">
                                <li><a href="~/" class="active">Ana Sayfa</a></li>
                                @{ Html.RenderAction("KategoriMenu", "Menu");}
                                
                            </ul>
                        </div>
                    </div>
                   
                </div>
            </div>
        </div>
	
	</header><!--/header-->
  
    @if (ViewBag.Manset == true)
    {
        Html.RenderAction("Manset", "Mansetler");
        <br />
            }
 
   
    <section>
        <div class="container">
            <div class="row">
               
                
                <div class="col-sm-12 padding-center">
                    <div class="features_items">
                        <!--features_items-->
                        <h2 class="title text-center" style="margin-left:auto;margin-right:auto">@ViewBag.Baslik</h2>
                        @RenderBody()


                    </div><!--features_items-->

                </div>
            </div>
        </div>
    </section>

    <footer id="footer">
        <!--Footer-->
        <div class="footer-bottom">
            <div class="container">
                <div class="row">
                    <p class="pull-left">Copyright © 2016 Habercim </p>
                    <p class="pull-right">Haberde Son Dakika</p>
                </div>
            </div>
        </div>

    </footer><!--/Footer-->

    <script src="~/Content/js/jquery.js"></script>
    <script src="~/Content/js/bootstrap.min.js"></script>
    <script src="~/Content/js/jquery.scrollUp.min.js"></script>
    <script src="~/Content/js/price-range.js"></script>
    <script src="~/Content/js/jquery.prettyPhoto.js"></script>
    <script src="~/Content/js/main.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

















































@*<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>*@