Habercim/Habercim/Models/Haber.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Habercim.Models
{
    public class Haber
    {
        public int HaberId { get; set; }
        public string Resim { get; set; }
        public string Baslik { get; set; }
        public string Aciklama { get; set; }
        public string Metin { get; set; }
        public DateTime Tarih { get; set; }
        public int TurId { get; set; }
        public virtual Tur Tur { get; set; }
        public ICollection<Begeni> Begeniler { get; set; }
        public ICollection<Yorum> Yorumlar { get; set; }


    }
}

Habercim/Habercim/Areas/Admin/Controllers/HaberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Habercim.DAL;
using Habercim.Models;
using Habercim.Models.Helpers;
using System.IO;

namespace Habercim.Areas.Admin.Controllers
{
    public class HaberController : GirisController
    {
        private HabercimDbContext db = new HabercimDbContext();

        // GET: Admin/Haber
        public ActionResult Index()
        {
            var haberler = db.Haberler.Include(h => h.Tur);
            return View(haberler.ToList());
        }

        // GET: Admin/Haber/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Haber haber = db.Haberler.Find(id);
            if (haber == null)
            {
                return HttpNotFound();
            }
            return View(haber);
        }

        const string imageFolderPath = "/Content/images/haberler/";
        // GET: Admin/Haber/Create
        public ActionResult Create()
        {
            ViewBag.TurId = new SelectList(db.Turler, "TurId", "TurAd");
            return View();
        }

        // POST: Admin/Haber/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(HaberEkle eklenecekHaber)
        {
            if (ModelState.IsValid)
            {

                string fileName = string.Empty;

                if (eklenecekHaber.Resim != null && eklenecekHaber.Resim.ContentLength > 0)
                {
                    fileName = eklenecekHaber.Resim.FileName;
                    var path = Path.Combine(Server.MapPath(imageFolderPath), fileName);
                    /* eger varsa sil */
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                    eklenecekHaber.Resim.SaveAs(path);
                }
                Haber haber = new Haber();
                haber.Aciklama = eklenecekHaber.Aciklama;
                haber.Baslik = eklenecekHaber.Baslik;
                haber.Metin = eklenecekHaber.Metin;
                haber.Tarih = DateTime.Now;
                haber.TurId = eklenecekHaber.TurId;
                haber.Resim= imageFolderPath + fileName;
                db.Haberler.Add(haber);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.TurId = new SelectList(db.Turler, "TurId", "TurAd", eklenecekHaber.TurId);
            return View(eklenecekHaber);
        }

        // GET: Admin/Haber/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Haber haber = db.Haberler.Find(id);
            if (haber == null)
            {
                return HttpNotFound();
            }
            HaberEkle degisecekHaber = new HaberEkle();
            degisecekHaber.HaberId = haber.HaberId;
            degisecekHaber.Aciklama = haber.Aciklama;
            degisecekHaber.Baslik = haber.Baslik;
            degisecekHaber.Metin = haber.Metin;
            degisecekHaber.ResimUrl = haber.Resim;
            degisecekHaber.TurId = haber.TurId;
            ViewBag.TurId = new SelectList(db.Turler, "TurId", "TurAd", haber.TurId);
            return View(degisecekHaber);
        }

        // POST: Admin/Haber/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(HaberEkle degisHaber)
        {
            if (ModelState.IsValid)
            {
                string fileName = string.Empty;

                if (degisHaber.Resim != null && degisHaber.Resim.ContentLength > 0)
                {
                    fileName = degisHaber.Resim.FileName;
                    var path = Path.Combine(Server.MapPath(imageFolderPath), fileName);
                    /* eger varsa sil */
                    if (System.IO.File.Exists(path))
                    {
                        System.IO.File.Delete(path);
                    }
                    degisHaber.Resim.SaveAs(path);
                }
                var haber = db.Haberler.Find(degisHaber.HaberId);
                haber.Aciklama = degisHaber.Aciklama;
                haber.Baslik = degisHaber.Baslik;
                haber.Metin = degisHaber.Metin;
                haber.Tarih = DateTime.Now;
                haber.TurId = degisHaber.TurId;
                if (degisHaber.Resim != null)
                {
                    haber.Resim = imageFolderPath + fileName;
                }
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.TurId = new SelectList(db.Turler, "TurId", "TurAd", degisHaber.TurId);
            return View(degisHaber);
        }

        // GET: Admin/Haber/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Haber haber = db.Haberler.Find(id);
            if (haber == null)
            {
                return HttpNotFound();
            }
            return View(haber);
        }

        // POST: Admin/Haber/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Haber haber = db.Haberler.Find(id);
            db.Haberler.Remove(haber);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Habercim/Habercim/Areas/Admin/Views/Haber/Create.cshtml
@model Habercim.Models.Helpers.HaberEkle
@{
    ViewBag.Title = "Yeni Haber";
}

<h2>Yeni Haber</h2>


@using (Html.BeginForm("Create", "Haber", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Haber</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Resim, new { @class = "form-control", placeholder = "Resim", type = "file" })
                @Html.ValidationMessageFor(model => model.Resim, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Metin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Metin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Metin, "", new { @class = "text-danger" })
            </div>
        </div>

       

        <div class="form-group">
            @Html.LabelFor(model => model.TurId, "TurId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TurId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TurId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Oluştur" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Haberlere Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Habercim/Habercim/Areas/Admin/Views/Haber/Delete.cshtml
@model Habercim.Models.Haber

@{
    ViewBag.Title = "Haber Sil";
}

<h2>Haber Sil</h2>

<h3>Bunu silmek istediğinize emin misiniz?</h3>
<div>
    <h4>Haber</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tur.TurAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tur.TurAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Metin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Metin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Sil" class="btn btn-default" /> |
            @Html.ActionLink("Haberlere Geri Dön", "Index")
        </div>
    }
</div>

Habercim/Habercim/Areas/Admin/Views/Haber/Details.cshtml
@model Habercim.Models.Haber

@{
    ViewBag.Title = "Detaylar";
}

<h2>Detaylar</h2>

<div>
    <h4>Haber</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Tur.TurAd)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tur.TurAd)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Resim)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Resim)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Baslik)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Baslik)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Aciklama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Aciklama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Metin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Metin)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Tarih)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Tarih)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Düzenle", "Edit", new { id = Model.HaberId }) |
    @Html.ActionLink("Haberlere Geri Dön", "Index")
</p>

Habercim/Habercim/Areas/Admin/Views/Haber/Edit.cshtml
@model Habercim.Models.Helpers.HaberEkle

@{
    ViewBag.Title = "Haber Düzenle";
}

<h2>Haber Düzenle</h2>


@using (Html.BeginForm("Edit", "Haber", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Haber</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.HaberId)

        <div class="form-group">
            @Html.LabelFor(model => model.Resim, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Resim, new { @class = "form-control", placeholder = "Resim", type = "file" })
                @Html.ValidationMessageFor(model => model.Resim, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Baslik, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Baslik, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Baslik, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Aciklama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Aciklama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Aciklama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Metin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Metin, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Metin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TurId, "TurId", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("TurId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.TurId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Kaydet" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Haberlere Geri Dön", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Habercim/Habercim/Areas/Admin/Views/Haber/Index.cshtml
@model IEnumerable<Habercim.Models.Haber>

@{
    ViewBag.Title = "Haberler";
}

<h2>Haberler</h2>

<p>
    @Html.ActionLink("Yeni Haber", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Tur.TurAd)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Resim)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Baslik)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Aciklama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Metin)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tarih)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Tur.TurAd)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Resim)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Baslik)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Aciklama)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Metin)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Tarih)
        </td>
        <td>
            @Html.ActionLink("Düzenle", "Edit", new { id=item.HaberId }) |
            @Html.ActionLink("Detaylar", "Details", new { id=item.HaberId }) |
            @Html.ActionLink("Sil", "Delete", new { id=item.HaberId })
        </td>
    </tr>
}

</table>